// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3WolnZAfFUgqkXOsb3b76Gm9h7BBiX-4',
    appId: '1:709979235138:web:d989e4702797b0b6badedb',
    messagingSenderId: '709979235138',
    projectId: 'vgo-app-cf997',
    authDomain: 'vgo-app-cf997.firebaseapp.com',
    storageBucket: 'vgo-app-cf997.appspot.com',
    measurementId: 'G-PJC795DGJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSY073oBXD_ics96OIX_JUEcZ5fx5N_XY',
    appId: '1:709979235138:android:5c5194dbc7feaeedbadedb',
    messagingSenderId: '709979235138',
    projectId: 'vgo-app-cf997',
    storageBucket: 'vgo-app-cf997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNxPTq31nTDCk2KdhtTvhKrikrf78N9Y',
    appId: '1:709979235138:ios:d6ab280ef89c5fd7badedb',
    messagingSenderId: '709979235138',
    projectId: 'vgo-app-cf997',
    storageBucket: 'vgo-app-cf997.appspot.com',
    iosClientId: '709979235138-dgpr52jg5k3go9139aumnlq0370pauok.apps.googleusercontent.com',
    iosBundleId: 'com.oenghokleng.vgoApp',
  );
}
